### ISSUE TITLE
Use sister crate to control version of the C++ library

### ISSUE THREAD

**Issue by TDHolmes** [rust-rpi-led-matrix/rust-rpi-rgb-led-matrix#1]
We often get broken by the C++ library we depend on. Locking that version in a sister crate that has the library checked out as a submodule would prevent this.

**Comment by TDHolmes** [comment]
cc. @sphinxc0re

**Comment by sphinxc0re** [comment]
Yup 🙂 I'm on vacation right now but I will put up the repo I built as soon as I'm back home. It does exactly what you just said. I haven't thought about crate versioning yet. Does the Hzeller code have tags?

**Comment by TDHolmes** [comment]
Sweet Sounds good! It doesn’t look like it... might have to just update on
demand or something

**Comment by sphinxc0re** [comment]
Sorry, that this is taking such a long time... I'm going through some stuff right now 😅

**Comment by TDHolmes** [comment]
no worries! I definitely know how that goes - my contributions will ebb and flow too 😛

**Comment by TDHolmes** [comment]
Hey @sphinxc0re, got any time for this soon? I'm thinking about giving it a crack

**Comment by sphinxc0re** [comment]
I'm back to being able to work on this :sweat_smile: I'll try to fit it in this Sunday

**Comment by sphinxc0re** [comment]
Sorry... I didn't get to it. I'll try doing it this week..

**Comment by TDHolmes** [comment]
No worries :) was mainly just wondering if you were still interested in this. No huge rush
