### ISSUE TITLE
rpi-rgb-led-matrix links to libstdc++ dynamically hence impossible to generate statically linked binary

### ISSUE THREAD

**Issue by windoze** [rust-rpi-led-matrix/rust-rpi-rgb-led-matrix#26]
In the `build.rs` of the sys crate, the script forces to use dynamic libstdc++:
https://github.com/rust-rpi-led-matrix/rust-rpi-rgb-led-matrix/blob/e32b7ddeb7df93da8f269d7432a422cff8420bd6/rpi-led-matrix-sys/build.rs#L17
Before the separation of Rust API and FFI packages, I was able to generate statically linked binary as I did in my [neoclock](https://github.com/windoze/neoclock) project, but it's not the case in the new version.

**Comment by TDHolmes** [comment]
hmm, even before the split this was in the `build.rs` script ([see here](https://github.com/rust-rpi-led-matrix/rust-rpi-rgb-led-matrix/blob/507fa560a04a20cc1bbfa5cd83d81c6efafddfdd/build.rs#L4)). Why do you want static linking instead of dynamic to the std library?

I'll look into making this configurable either way

**Comment by windoze** [comment]
I was aware of this line before, and I managed the "fix" it with [some hacks](https://github.com/windoze/neoclock/blob/main/linker), but it's broken after the upgrading, I'm still working on an adhoc workaround but I think it's better to add this feature in the upstream.
Yes I know it looks pretty ugly but it seems to be the only way I can find to make Rust stay peace with libstdc++ in a statically linked binary.

As to the statically linked binary itself, it makes my life easier to cross compile RPi programs, without need to prepare a sysroot with full blown RPi system image, it's always a PITA when you need to update packages inside of such kind of environment as you cannot run `apt update` on host.

After all, thanks for your effort make this convenient crate, I created a toy clock with this package and some LEGO bricks and got a lot of fun from it.

**Comment by TDHolmes** [comment]
Thanks for the explanation and pointers! Glad you found this crate useful,
it’s cool hearing what people have done with it. I’ll try to fix this. If
you find a good way let me know

**Comment by TDHolmes** [comment]
Where are you seeing `libstdc++.a`? I only see `.so` variants which means dynamic linking only

**Comment by windoze** [comment]
In order to link statically, you'll need musl instead of glibc, and build libstdc++ on top of it by yourself, you can choose to build libstdc++.a and/or libstdc++.so at the moment you setup the toolchain.
There is a prebuilt toolchain and Docker image at https://github.com/messense/rust-musl-cross, with it you can easily cross compile Rust code on any Linux host.
I recommend not to compile Rust or big C++ project on RPi directly, the process is much slower than any decent desktop computer, even sometimes it may destroy your TF card.

**Comment by TDHolmes** [comment]
Thanks, I'll get that installed. Since by default this is't available on a stock pi, I think this will be an opt-in feature folks can enable if they want it.

**Comment by windoze** [comment]
Sure it should be an optional feature and disabled by default, I was thinking of configuring toolchains with cargo features but didn't find a proper way.

PS. `libstdc++.a` exists in stock Raspberry Pi OS under `/usr/lib/gcc/arm-linux-gnueabihf/{GCC_VER}` directory, and you can generate statically linked binary on RPi with `g++ -static`.

**Comment by TDHolmes** [comment]
Thanks for the tip! using that `libstdc++.a`, looks like I'm able to statically link. Can you try out the branch and confirm if it works for you too?

**Comment by windoze** [comment]
Tried the "static-link" branch and it said "rpi-led-matrix-sys detected you're likely not compiling on a raspberry pi".
Am I looking at the wrong place?

**Comment by TDHolmes** [comment]
ah, I forgot to change the build script from checking `HOST` to `TARGET` to support cross-compilation. I just pushed a fix, can you try again? That is the right branch.

**Comment by windoze** [comment]
Just tried and it works with quite a long command
```
docker run \
--rm -it --user "$(id -u):$(id -g)" \
--env CC=/usr/local/musl/bin/armv7-unknown-linux-musleabihf-cc \
--env CXX=/usr/local/musl/bin/armv7-unknown-linux-musleabihf-c++ \
--env AR=/usr/local/musl/bin/armv7-unknown-linux-musleabihf-ar \
-v "$HOME/.cargo":/root/.cargo \
-v "$(pwd)":/home/rust/src messense/rust-musl-cross:armv7-musleabihf \
cargo build --release
```

The only issue is that you're using a private link to the original LedMatrix C++ repo, which I don't have access to:

https://github.com/rust-rpi-led-matrix/rust-rpi-rgb-led-matrix/blob/1e8219d6a2347a10fd488614086fe30c4eaf8872/.gitmodules#L3

**Comment by TDHolmes** [comment]
This would require SSH keys to be set up for it to work but other than that it should be fine. This also won't be an issue once I submit it to crates.io. Thanks for trying it out! I'll do a release soon

**Comment by windoze** [comment]
Thank you for this crate and everything you've done to help me 😄

**Comment by TDHolmes** [comment]
Happy to help! Just published the new version, let me know if it doesn't work for you as expected

**Comment by windoze** [comment]
Works like a charm 😆 
Thanks a lot!
