### ISSUE TITLE
Rust rewrite

### ISSUE THREAD

**Issue by EmbersArc** [rust-rpi-led-matrix/rust-rpi-rgb-led-matrix#37]
I've been working on a complete [rewrite of the library in Rust](https://github.com/EmbersArc/rpi_led_panel). Originally it was just for shits and giggles but has now reached a state where I feel comfortable publishing it. Maybe somebody here is interested in using it or even contributing.

**Comment by TDHolmes** [comment]
Looks awesome! Definitely worth nudging folks towards if they're interested in a pure Rust option
